apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unmanic
  namespace: unmanic
  labels:
    app: unmanic
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    hajimari.io/enable: "true"
    hajimari.io/icon: https://avatars.githubusercontent.com/u/81266068
spec:
  ingressClassName: traefik
  rules:
    - host: unmanic.homelab.olav.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unmanic-service
                port:
                  number: 8888
  tls:
    - hosts:
        - unmanic.homelab.olav.ninja
      secretName: unmanic-tls-certificate
