apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./aria2
  - ./bambustudio
  - ./fileflows
  - ./gitea
  - ./homeassistant
  - ./immich
  - ./nextcloud
  - ./ollama
  - ./openwebui
  - ./pingvinshare
  - ./samba

