apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openwebui

resources:
  - namespace.yaml
  - oidc-client.yaml
  - pvcs.yaml
  - secrets.yaml
  - middleware.yaml

helmCharts:
  - name: open-webui
    releaseName: openwebui
    namespace: openwebui
    repo: https://helm.openwebui.com/
    version: 8.22.0
    valuesFile: values.yaml

patches:
  - path: patches/add-sablier-labels.yaml
  - path: patches/remove-replicas.yaml
    target:
      kind: StatefulSet
      name: open-webui
