apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fileflows

resources:
  - namespace.yaml
  - oidc-client.yaml
  - middleware.yaml
  - pvcs.yaml
  - secrets.yaml

helmCharts:
  - name: fileflows
    releaseName: fileflows
    namespace: fileflows
    repo: oci://oci.trueforge.org/truecharts
    version: 14.18.5
    valuesFile: values.yaml

