apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-tls-certificate
  namespace: traefik
spec:
  secretName: traefik-dashboard-tls-certificate
  dnsNames:
    - traefik.homelab.olav.ninja
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: letsencrypt
