---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-oidc-credentials
  namespace: traefik
spec:
  encryptedData:
    clientSecret: AgCX1fRQjNjNrsty362dIo7120zyvbXLn6GfNludE3W04OWOQ8FSGkWFbA8QrNcCwDxz9YCdpTU/Kyq7SOWMOhyjTSOdxyK0WtiZdFoK1zEf2dJFs9ttGJy5nAttqLqUbGM1OAesUA08+GMRPjPznQ0sDy1k6h1nnvbswVQpTmivUCNvVkGxtWn3Mp5MoLkTDAKkVLNWQqccMZiW+bvNZhMXwZJvdQbCck/ZEH0lI4n1RzDyRCmgoygcmx26buKx/IXLwvAn4G5NxtmuEMIBuRomx1Q7cgumfZuLTvx0Nmo1afwmv6bTNt0h/aWr5ypNQeZTXxUsDnRKzaHfJujxbx2Gy1fxB3FbVs/nZv7IvjGEqfbW47tJjyqNUinw8Jvk5RnI7mHHrEubrurA/r2MfMh45dWcyQNO2J9Yr01jZI1Whbw8Q8w5c1+n/slkvRc4KvOmjEMqovHyupsxVowWLW+ozAq/R1T4vvwlVcVoMJIXxphktr1nrX+UwpawOL78MjMn8wxrFCgmvHxVtrAjtxgJgH0JBRdGYUy8gWMALMlrEXykJ6sAqvN9KZ6FYtqERTeRklFG/+ZoottM4ms7Tjt2/HbQHYbWvQpr80q7MYwTmv5V8hcNIm0jKmHBxgYrrIDkj4oAPtci85s23OAAh6ARAfaPL2/owcuWSIovRXdNU4WqqT19lT3oTVMlMm3k1DCHdNznY60LZonjNhni9VIbUrj59fkdVk2JZZWVWJkrCw==
    pluginSecret: AgAhoWHxVOI2pmf5r6DT3x30Kwv5V71rtlq2lJyHMKNvv56XFE1xQV/fOA9+3BOnOvDNLHbaMswsSfjilnfjjShARh4PqFmqqj7fYRAy4YvUIuzMifo2nF6tDL6nB+jhtH56gi1zXeFD2Ua8UnnpRDDreD251Zqm0MeWU9p+6szNF/F72zy7/lgudmSr5XRdEKsCjpYzop/kOOSeI/0SFHP2E/LzFPKQ4ufAt8ktg7rMcqrZIRDybrAmQP1eXqLhbz52iBe5zZNPBLfqlT1nJxG6zK6O3cN9Sk800mmSdYiFZj4tPpIA70AWRZv49W8eesapAsngTxw7wG8NdYuYO6UOQCTGy6RoeYmqC/oKHqwKOQBImg/uhMmYKgknKLoFrddtCRKFs6fMiNuQEXNlUR/cuzNXSA8E556Bd30ZxetHhM8MRFZIgy7bR2CJf0gbhRmlXeUrd9XQ81G9b3JqJmfHn1h+bsmxxrFA0JGwI9x+HD62Zr5f4CBctCV62azB3cqrFKeB+6ph8Ez2eA6nwNB2N8IbiwFcgRwtGO9MjnFEeRhKpbHEMECEaFw8/lnX/zgIn08mljU17CRLUCPPVy/nO+kE6GTPatuBRjUz4EGLw5nDPOhBniIcSybyW/Uc8QCow+wWn083VRXPzxtAXPM3jQBuCzWtCoFa2gbrLuxlB8YOxn4+UInlEPrNHLdVRRqsZF/+LbsRHF57geqRlgWT3j25Kr+De8kIysnvYAB/hg==
  template:
    metadata:
      name: traefik-oidc-credentials
      namespace: traefik
