# deployment:
#   podAnnotations:
#     netbird.io/setup-key: traefik

ingressRoute:
  dashboard:
    enabled: false

service:
  type: LoadBalancer
  annotations:
    netbird.io/expose: true
    netbird.io/groups: cluster
    netbird.io/policy: cluster
    external-dns.alpha.kubernetes.io/internal-hostname: "homelab.olav.ninja,*.homelab.olav.ninja"
  spec:
    externalTrafficPolicy: Local
    internalTrafficPolicy: Local
    clusterIP: 10.96.100.100
    loadBalancerIP: 192.168.0.90

providers:
  kubernetesIngress:
    publishedService:
      enabled: true
      pathOverride: "traefik/traefik"

ports:
  web:
    expose:
      default: false
  websecure:
    asDefault: true
    expose:
      default: true
    exposedPort: 443
    tls:
      enabled: true
    middlewares:
      - traefik-securityheaders@kubernetescrd
    transport:
      respondingTimeouts:
        readTimeout: 0 # Required for Netbird signal GRPC
  webpublic:
    expose:
      default: true
    port: 9443
    containerPort: 9443
    exposedPort: 9443
    tls:
      enabled: true
    middlewares:
      - traefik-securityheaders@kubernetescrd
    transport:
      respondingTimeouts:
        readTimeout: 0 # Required for Netbird signal GRPC
  ssh:
    expose:
      default: true
    port: 2222
    containerPort: 2222
    exposedPort: 22

experimental:
  plugins:
    sablier:
      moduleName: github.com/sablierapp/sablier-traefik-plugin
      version: v1.1.0 # renovate: github-releases=sablierapp/sablier-traefik-plugin
