apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama

resources:
  - namespace.yaml
  - middleware.yaml

helmCharts:
  - name: ollama
    releaseName: ollama
    namespace: ollama
    repo: https://otwld.github.io/ollama-helm/
    version: 1.40.0
    valuesFile: values.yaml

patches:
  - path: patches/use-intel-gpu.yaml
  - path: patches/remove-replicas.yaml
    target:
      kind: Deployment
      name: ollama
