apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier
spec:
  plugin:
    sablier:
      group: ollama-openwebui # Shared group with openwebui
      dynamic:
        displayName: Ollama / Open WebUI
        refreshFrequency: 5s
        showDetails: "true"
        theme: ghost
      sablierUrl: http://sablier-sablier.sablier.svc.cluster.local:10000
      sessionDuration: 1h
