apiVersion: v1
kind: Service
metadata:
  annotations:
    netbird.io/expose: true
    netbird.io/groups: cluster
    netbird.io/policy: cluster
    io.cilium/lb-ipam-ips: 192.168.0.92
  name: samba
  namespace: samba
spec:
  type: LoadBalancer
  selector:
    app: samba
  ports:
    - port: 445
      targetPort: 445
      protocol: TCP
      name: smb
