apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: samba
  namespace: samba
spec:
  serviceName: samba
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command:
          - sh
          - -c
          - |
            chown -R 65534:65534 /mnt/media
            chmod -R 775 /mnt/media
          volumeMounts:
          - mountPath: /mnt/media
            name: media-storage
          securityContext:
            runAsUser: 0
      containers:
        - name: samba
          image: quay.io/samba.org/samba-server:v0.8 # renovate: docker=quay.io/samba.org/samba-server
          ports:
            - containerPort: 445
              name: smb
              protocol: TCP
          env:
            - name: SAMBACC_CONFIG
              value: /etc/samba-container/config.json
            - name: SAMBA_CONTAINER_ID
              value: samba
          volumeMounts:
            - name: samba-config
              mountPath: /etc/samba-container
              readOnly: true
            - name: media-storage
              mountPath: /mnt/media
      volumes:
        - name: samba-config
          configMap:
            name: samba-config
            items:
            - key: config.json
              path: config.json
        - name: media-storage
          hostPath:
            path: /var/mnt/bulk-storage/shares/media
            type: DirectoryOrCreate
