apiVersion: apps/v1
kind: Deployment
metadata:
  name: aria2
  labels:
    app: aria2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aria2
  template:
    metadata:
      labels:
        app: aria2
    spec:
      containers:
        - name: aria2
          image: hurlenko/aria2-ariang:1.3.12 # renovate: docker=hurlenko/aria2-ariang
          env:
            - name: PUID
              value: "65534" # "nobody" user in samba container
            - name: PGID
              value: "65534"
            - name: RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: aria2-secrets
                  key: RPC_SECRET
            - name: EMBED_RPC_SECRET
              value: "true"
            - name: ARIA2RPCPORT
              value: "443"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
            - name: aria2-config
              mountPath: /aria2/conf
            - name: aria2-data
              mountPath: /aria2/data
      volumes:
        - name: aria2-config
          persistentVolumeClaim:
            claimName: aria2-config
        - name: aria2-data
          hostPath:
            path: /var/mnt/bulk-storage
            type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1" # Fix for alpine DNS issue
