apiVersion: apps/v1
kind: Deployment
metadata:
  name: aria2
  labels:
    app: aria2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aria2
  template:
    metadata:
      labels:
        app: aria2
    spec:
      containers:
        - name: aria2
          image: hurlenko/aria2-ariang:1.3.12 # renovate: docker=hurlenko/aria2-ariang
          env:
            - name: PUID
              value: "65534" # "nobody" user in samba container
            - name: PGID
              value: "65534"
            - name: RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: aria2-secrets
                  key: RPC_SECRET
            - name: EMBED_RPC_SECRET
              value: "true"
            - name: ARIA2RPCPORT
              value: "443"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
            - name: aria2-config
              mountPath: /aria2/conf
            - name: aria2-data
              mountPath: /aria2/data
      volumes:
        - name: aria2-config
          persistentVolumeClaim:
            claimName: aria2-config
        - name: aria2-data
          hostPath:
            path: /var/mnt/bulk-storage
            type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1" # Fix for alpine DNS issue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.13.0 # renovate: docker=quay.io/oauth2-proxy/oauth2-proxy
          args:
            - --provider=oidc
            - --oidc-issuer-url=https://keycloak.homelab.olav.ninja/realms/homelab
            - --client-id=aria2
            - --email-domain=*
            - --upstream=http://aria2:8080
            - --http-address=0.0.0.0:4180
            - --redirect-url=https://aria2.homelab.olav.ninja/oauth2/callback
            - --cookie-secure=true
            - --cookie-domain=.homelab.olav.ninja
            - --whitelist-domain=.homelab.olav.ninja
            - --pass-access-token=true
            - --set-xauthrequest=true
            - --skip-provider-button=true
            - --insecure-oidc-allow-unverified-email=true
          env:
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aria2-oidc-credentials
                  key: clientSecret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: aria2-oidc-credentials
                  key: cookieSecret
          ports:
            - containerPort: 4180
              protocol: TCP
              name: oauth2-proxy
