apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aria2
  namespace: aria2
  labels:
    app: aria2
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    hajimari.io/enable: "true"
    hajimari.io/icon: https://avatars.githubusercontent.com/u/13545224
spec:
  ingressClassName: traefik
  rules:
    - host: aria2.homelab.olav.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  name: oauth2-proxy
  tls:
    - hosts:
        - aria2.homelab.olav.ninja
      secretName: aria2-tls-certificate
