apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aria2

resources:
  - namespace.yaml
  - deployments.yaml
  - services.yaml
  - oidc-client.yaml
  - ingress.yaml
  - pvc.yaml
  - secrets.yaml

patches:
  - path: patches/add-gluetun-sidecar.yaml
