apiVersion: v1
kind: Service
metadata:
  name: aria2
spec:
  selector:
    app: aria2
  type: ClusterIP
  ports:
   - name: aria2-port
     port: 8080
     targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  type: ClusterIP
  ports:
    - name: oauth2-proxy
      port: 4180
      targetPort: 4180
