apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-oidc-credentials
  namespace: jellyfin
spec:
  encryptedData:
    clientSecret: AgAcHPYxBlVrQLIPis4i4iPpxgwPm1gyHSGGg50dDHaXKNKXZZxCHEpohlVZYzRjgqLjy+5464ztWasaAevy9NDAgAo1toJNtKVU4EfQNLoVoiCmW43Wz1ReOqgIJZVO9tAlPGdtZaovcURxvG3NOp/WvXsnFlpD6p3OMpdRICCoe34OiwI39eZRd1YZ2IHXsGtJWVA5mMIpTQj6Eoe6CZSQneVgjybnWpFOa6NgYD9T65K/NYQmG/o4/XpPyGQ5JtIzJoJwuqOE0W5NoKB99XyRVQ+2Tq6yuZTOCMgri+t1fsKAkYaUE4ROTPOsXIJA/fR/SOiz+RHkrMs+Hpb3xRofTYIrYbejYWGVrWHLimrJXcegiB3ntehdP5xbrmSf7Btb5pqZm/QPCxGkqS3a9LNjvZmJeUmGQUXngnxvg1GtsAnfXIzUm/aXYlkf9m5NKaYHqsfYDrTFzBRoYHBqo9LgBZrgmVytZMGGaOpZh6kWMNoko/ScG1zipClYtKj40LJrSbJywEYQzjB8O6JfgfCdvp9yCr+ICelsdoa/fTwS9tThlnBUchU/tA8AjMsreL7NowdqbmYqvx2F0jckXTfhQeOB9+8m3kVcVPx+E5FqyejWOu7wka7o5ywP48TiJJclTePYIJkauFYVq1gTp5seAxFf5R3mKwhUg3nXllsJ7ZkQ9RqxiCiwdTjw46q36wYJKcHJeTnnUuO9f293tDfNpdYPuOPhP3A=
  template:
    metadata:
      name: jellyfin-oidc-credentials
      namespace: jellyfin
